# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/kroki"

# [params.hb.kroki]

# [params.hugopress.modules.hb-kroki.hooks.body-end]
# cacheable = true
